# Generated by Django 5.1.1 on 2025-10-20 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in gallery', verbose_name='Order')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('site_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_gallery_items', to='core.siteimage', verbose_name='Site Image')),
            ],
            options={
                'verbose_name': 'News Gallery Image',
                'verbose_name_plural': 'News Gallery Images',
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_pt', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Featured Image')),
                ('content', models.TextField(help_text='Rich content for the news post', verbose_name='Content')),
                ('content_pt', models.TextField(help_text='Rich content for the news post', null=True, verbose_name='Content')),
                ('content_en', models.TextField(help_text='Rich content for the news post', null=True, verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary of the news post', max_length=300, verbose_name='Excerpt')),
                ('excerpt_pt', models.TextField(blank=True, help_text='Short summary of the news post', max_length=300, null=True, verbose_name='Excerpt')),
                ('excerpt_en', models.TextField(blank=True, help_text='Short summary of the news post', max_length=300, null=True, verbose_name='Excerpt')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_description_pt', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('gallery_images', models.ManyToManyField(blank=True, related_name='news_posts', through='news.NewsGalleryImage', to='core.siteimage', verbose_name='Gallery Images')),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newsgalleryimage',
            name='news_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='news.newspost', verbose_name='News Post'),
        ),
        migrations.AlterUniqueTogether(
            name='newsgalleryimage',
            unique_together={('news_post', 'site_image')},
        ),
    ]
