# Generated by Django 5.1.1 on 2025-10-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='content_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Conteúdo PT", "en": "Content EN"}', verbose_name='Content (All Languages)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Resumo PT", "en": "Excerpt EN"}', verbose_name='Excerpt (All Languages)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='meta_description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Meta descrição PT", "en": "Meta description EN"}', verbose_name='Meta Description (All Languages)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Título PT", "en": "Title EN"}', verbose_name='Title (All Languages)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Content (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Content (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Excerpt (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Excerpt (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='excerpt_pt',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Excerpt (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='meta_description_pt',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (OLD)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (OLD)'),
        ),
    ]
