# Generated by Django 5.1.1 on 2025-10-28 00:20

from django.db import migrations
from django.conf import settings


def copy_newspost_to_json(apps, schema_editor):
    """Copy NewsPost data from modeltranslation fields to JSON fields"""
    NewsPost = apps.get_model('news', 'NewsPost')

    languages = [code for code, name in settings.LANGUAGES]

    for obj in NewsPost.objects.all():
        # Migrate title
        obj.title_i18n = {}
        for lang in languages:
            field_name = f'title_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.title_i18n[lang] = value

        # Migrate content
        obj.content_i18n = {}
        for lang in languages:
            field_name = f'content_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.content_i18n[lang] = value

        # Migrate excerpt
        obj.excerpt_i18n = {}
        for lang in languages:
            field_name = f'excerpt_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.excerpt_i18n[lang] = value

        # Migrate meta_description
        obj.meta_description_i18n = {}
        for lang in languages:
            field_name = f'meta_description_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.meta_description_i18n[lang] = value

        obj.save()
        print(f"✓ Migrated NewsPost: {obj.slug} - {obj.title_i18n}")


def reverse_migration(apps, schema_editor):
    """Reverse migration"""
    print("Reversing migration...")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspost_content_i18n_newspost_excerpt_i18n_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_newspost_to_json, reverse_migration),
    ]
