# Generated by Django 5.1.1 on 2025-10-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_copy_data_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='content_pt',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='excerpt_pt',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='meta_description_pt',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='title_pt',
        ),
    ]
