# Generated by Django 6.0.2 on 2026-03-04 11:44

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newspost_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_i18n', models.JSONField(blank=True, default=dict, help_text='{"pt": "Tecnologia", "en": "Technology"}', verbose_name='Name (All Languages)')),
                ('slug_i18n', models.JSONField(blank=True, default=dict, help_text='{"pt": "tecnologia", "en": "technology"}', verbose_name='Slug (All Languages)')),
                ('description_i18n', models.JSONField(blank=True, default=dict, verbose_name='Description (All Languages)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['order', 'pk'],
            },
            bases=(core.mixins.I18nModelMixin, models.Model),
        ),
    ]
