# Generated by Django 6.0.2 on 2026-03-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news.newscategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='html_content_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Per-language HTML, same as Page model', verbose_name='HTML Content (All Languages)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='slug_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "meu-artigo", "en": "my-article"}', verbose_name='Slug (All Languages)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Conteúdo PT", "en": "Content EN"}', verbose_name='Content (All Languages) (OLD)'),
        ),
    ]
