# Generated by Django 6.0.2 on 2026-03-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_populate_i18n_html_fields'),
        ('news', '0009_add_news_layout'),
    ]

    operations = [
        # Clear empty string and non-numeric values from the old ImageField column
        # so the ALTER to FK doesn't fail on constraint checks
        migrations.RunSQL(
            "UPDATE news_newspost SET featured_image = NULL WHERE featured_image = '' OR featured_image IS NOT NULL AND typeof(featured_image) = 'text'",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_featured_posts', to='core.siteimage', verbose_name='Featured Image'),
        ),
    ]
