# Generated by Django 5.1.1 on 2025-10-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='html_template',
            field=models.TextField(blank=True, default='', help_text='HTML template for this section. Supports Django template syntax with {{trans.field}} variables. If empty, falls back to template file based on section_type.', verbose_name='HTML Template'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(help_text='Descriptive label for this section (e.g., "Hero Banner", "Pricing Table", "Team Grid")', max_length=100, verbose_name='Section Type'),
        ),
    ]
