# Generated by Django 5.1.1 on 2025-10-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sitesettings_excelencia_badge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='design',
        ),
        migrations.RemoveField(
            model_name='section',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='sectionversion',
            name='design',
        ),
        migrations.RemoveField(
            model_name='sectionversion',
            name='settings',
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.JSONField(default=dict, help_text='Translatable content ONLY: {"translations": {"pt": {"title": "...", "text": "..."}, "en": {...}}}. Do NOT store URLs, icons, or styling here - those belong in html_template.', verbose_name='Content'),
        ),
    ]
