# Generated by Django 5.1.1 on 2025-10-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_default_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "sobre", "en": "about"} - URL-friendly slugs for each language', verbose_name='Slug (All Languages)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug (OLD)'),
        ),
    ]
