# Generated by Django 5.1.1 on 2025-10-28 01:11

from django.db import migrations


def copy_slug_to_slug_i18n(apps, schema_editor):
    """
    Copy existing slug values to slug_i18n for all enabled languages.
    This allows each language to have its own slug (e.g., /pt/sobre/ vs /en/about/).
    """
    Page = apps.get_model('core', 'Page')
    SiteSettings = apps.get_model('core', 'SiteSettings')

    # Get enabled languages from SiteSettings
    site_settings = SiteSettings.objects.first()
    if site_settings and site_settings.enabled_languages:
        languages = [lang['code'] for lang in site_settings.enabled_languages]
    else:
        # Fallback to default languages
        languages = ['pt', 'en']

    # Copy slug to slug_i18n for each page
    for page in Page.objects.all():
        if page.slug:
            # Initialize slug_i18n with the same slug for all languages
            # Users can later customize per language in the admin
            page.slug_i18n = {lang: page.slug for lang in languages}
            page.save(update_fields=['slug_i18n'])
            print(f"Copied slug '{page.slug}' to slug_i18n for page: {page.title or page.slug}")


def reverse_copy(apps, schema_editor):
    """Reverse migration - copy first slug_i18n value back to slug"""
    Page = apps.get_model('core', 'Page')

    for page in Page.objects.all():
        if page.slug_i18n and isinstance(page.slug_i18n, dict) and page.slug_i18n:
            # Get first available slug from slug_i18n
            page.slug = list(page.slug_i18n.values())[0]
            page.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_slug_i18n_to_page'),
    ]

    operations = [
        migrations.RunPython(copy_slug_to_slug_i18n, reverse_copy),
    ]
