# Generated by Django 5.1.1 on 2025-10-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_update_pageversion_to_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent/highlight color', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Main background color', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='border_radius_preset',
            field=models.CharField(choices=[('none', 'None (0px)'), ('sm', 'Small (0.125rem)'), ('md', 'Medium (0.375rem)'), ('lg', 'Large (0.5rem)'), ('xl', 'Extra Large (0.75rem)'), ('2xl', '2XL (1rem)'), ('3xl', '3XL (1.5rem)'), ('full', 'Full (9999px)')], default='lg', help_text='Default border radius for cards, images, etc.', max_length=20, verbose_name='Border Radius'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_border_width',
            field=models.CharField(choices=[('0', 'None'), ('1', '1px'), ('2', '2px'), ('4', '4px')], default='0', help_text='Border width for buttons', max_length=10, verbose_name='Button Border Width'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='container_width',
            field=models.CharField(choices=[('full', 'Full Width'), ('xs', 'Extra Small (20rem)'), ('sm', 'Small (24rem)'), ('md', 'Medium (28rem)'), ('lg', 'Large (32rem)'), ('xl', 'Extra Large (36rem)'), ('2xl', '2XL (42rem)'), ('3xl', '3XL (48rem)'), ('4xl', '4XL (56rem)'), ('5xl', '5XL (64rem)'), ('6xl', '6XL (72rem)'), ('7xl', '7XL (80rem)')], default='7xl', help_text='Maximum width for main content container', max_length=20, verbose_name='Container Width'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h1_font',
            field=models.CharField(default='system-ui, -apple-system, sans-serif', help_text='Font family for H1 headings', max_length=100, verbose_name='H1 Font'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h1_size',
            field=models.CharField(default='text-5xl', help_text='Tailwind text size class (e.g., text-5xl)', max_length=20, verbose_name='H1 Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h2_font',
            field=models.CharField(default='system-ui, -apple-system, sans-serif', help_text='Font family for H2 headings', max_length=100, verbose_name='H2 Font'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h2_size',
            field=models.CharField(default='text-4xl', help_text='Tailwind text size class (e.g., text-4xl)', max_length=20, verbose_name='H2 Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h3_font',
            field=models.CharField(default='system-ui, -apple-system, sans-serif', help_text='Font family for H3 headings', max_length=100, verbose_name='H3 Font'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h3_size',
            field=models.CharField(default='text-3xl', help_text='Tailwind text size class (e.g., text-3xl)', max_length=20, verbose_name='H3 Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h4_font',
            field=models.CharField(default='system-ui, -apple-system, sans-serif', help_text='Font family for H4 headings', max_length=100, verbose_name='H4 Font'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h4_size',
            field=models.CharField(default='text-2xl', help_text='Tailwind text size class (e.g., text-2xl)', max_length=20, verbose_name='H4 Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h5_font',
            field=models.CharField(default='system-ui, -apple-system, sans-serif', help_text='Font family for H5 headings', max_length=100, verbose_name='H5 Font'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h5_size',
            field=models.CharField(default='text-xl', help_text='Tailwind text size class (e.g., text-xl)', max_length=20, verbose_name='H5 Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h6_font',
            field=models.CharField(default='system-ui, -apple-system, sans-serif', help_text='Font family for H6 headings', max_length=100, verbose_name='H6 Font'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='h6_size',
            field=models.CharField(default='text-lg', help_text='Tailwind text size class (e.g., text-lg)', max_length=20, verbose_name='H6 Size'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_button_bg',
            field=models.CharField(default='#1e3a8a', help_text='Background color for primary buttons', max_length=7, verbose_name='Primary Button Background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_button_border',
            field=models.CharField(default='#1e3a8a', help_text='Border color for primary buttons', max_length=7, verbose_name='Primary Button Border'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_button_hover',
            field=models.CharField(default='#1e40af', help_text='Hover background color for primary buttons', max_length=7, verbose_name='Primary Button Hover'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_button_text',
            field=models.CharField(default='#ffffff', help_text='Text color for primary buttons', max_length=7, verbose_name='Primary Button Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_button_bg',
            field=models.CharField(default='#64748b', help_text='Background color for secondary buttons', max_length=7, verbose_name='Secondary Button Background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_button_border',
            field=models.CharField(default='#64748b', help_text='Border color for secondary buttons', max_length=7, verbose_name='Secondary Button Border'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_button_hover',
            field=models.CharField(default='#475569', help_text='Hover background color for secondary buttons', max_length=7, verbose_name='Secondary Button Hover'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_button_text',
            field=models.CharField(default='#ffffff', help_text='Text color for secondary buttons', max_length=7, verbose_name='Secondary Button Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shadow_preset',
            field=models.CharField(choices=[('none', 'None'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra Large'), ('2xl', '2XL')], default='md', help_text='Default shadow style for cards and elevated elements', max_length=20, verbose_name='Shadow Preset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='spacing_scale',
            field=models.CharField(choices=[('tight', 'Tight (smaller gaps)'), ('normal', 'Normal'), ('relaxed', 'Relaxed (larger gaps)'), ('loose', 'Loose (largest gaps)')], default='normal', help_text='Spacing between sections and elements', max_length=20, verbose_name='Spacing Scale'),
        ),
    ]
