# Generated by Django 5.1.1 on 2025-10-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sitesettings_body_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Alternative logo for dark backgrounds (typically white/light version)', null=True, upload_to='site_images/', verbose_name='Logo (Dark Backgrounds)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main logo for light backgrounds', null=True, upload_to='site_images/', verbose_name='Logo (Light Backgrounds)'),
        ),
    ]
