# Generated by Django 5.1.1 on 2025-10-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesettings_logo_dark_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='logo_dark',
            new_name='logo_dark_bg',
        ),
    ]
