# Generated by Django 5.1.1 on 2025-10-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_globalsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='html_template',
        ),
        migrations.RemoveField(
            model_name='sectionversion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sectionversion',
            name='html_template',
        ),
        migrations.AddField(
            model_name='section',
            name='html_cache',
            field=models.TextField(blank=True, default='', help_text='Cached rendered HTML. Auto-generated from json_structure. Cleared on save.', verbose_name='HTML Cache'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_template',
            field=models.BooleanField(default=False, help_text='If true, this section is a reusable template in the component library', verbose_name='Is Template'),
        ),
        migrations.AddField(
            model_name='section',
            name='json_structure',
            field=models.JSONField(default=dict, help_text='Complete element tree with settings and content. Format: {"id": "...", "type": "container", "tag": "section", "settings": {...}, "content": {...}, "children": [...]}', verbose_name='JSON Structure'),
        ),
        migrations.AddField(
            model_name='section',
            name='template_category',
            field=models.CharField(blank=True, choices=[('hero', 'Hero'), ('features', 'Features'), ('cta', 'Call to Action'), ('about', 'About'), ('contact', 'Contact'), ('testimonials', 'Testimonials'), ('pricing', 'Pricing'), ('team', 'Team'), ('faq', 'FAQ'), ('other', 'Other')], default='', help_text='Category for organizing section templates', max_length=50, verbose_name='Template Category'),
        ),
        migrations.AddField(
            model_name='section',
            name='template_thumbnail',
            field=models.ImageField(blank=True, help_text='Preview image for template library', null=True, upload_to='section_templates/', verbose_name='Template Thumbnail'),
        ),
        migrations.AddField(
            model_name='sectionversion',
            name='json_structure',
            field=models.JSONField(default=dict, verbose_name='JSON Structure'),
        ),
    ]
