# Generated by Django 5.1.1 on 2026-02-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_create_homepage_clone'),
    ]

    operations = [
        # Add new fields first
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='{"translations": {"pt": {"field": "valor"}, "en": {"field": "value"}}}', verbose_name='Translations'),
        ),
        migrations.AddField(
            model_name='page',
            name='html_content',
            field=models.TextField(blank=True, default='', help_text='Full page HTML with Tailwind CSS. Use {{trans.field}} for translatable content. Use data-section="name" on <section> tags for LLM reference.', verbose_name='HTML Content'),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='Translations'),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='html_content',
            field=models.TextField(blank=True, default='', verbose_name='HTML Content'),
        ),
        # Delete Section-related models (drops entire tables, no need to remove fields first)
        migrations.DeleteModel(
            name='SectionVersion',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
