# Generated by Django 6.0.2 on 2026-02-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_project_briefing_i18n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Descrição SEO", "en": "SEO Description"} - Description shown in search results', verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Título SEO", "en": "SEO Title"} - Override the page title in search results', verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image shown when page is shared on social media', null=True, upload_to='site_images/', verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Site favicon (recommended: 32x32 or 48x48 PNG)', null=True, upload_to='site_images/', verbose_name='Favicon'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_i18n', models.JSONField(blank=True, default=dict, help_text='{"pt": "Início", "en": "Home"}', verbose_name='Label')),
                ('url', models.CharField(blank=True, default='', help_text='External or custom URL (used when no page is selected)', max_length=500, verbose_name='Custom URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Open in New Tab')),
                ('css_class', models.CharField(blank=True, default='', max_length=100, verbose_name='CSS Class')),
                ('page', models.ForeignKey(blank=True, help_text='Link to an internal page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
