# Generated by Django 6.0.2 on 2026-02-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_blueprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteimage',
            name='category',
        ),
    ]
