# Generated by Django 6.0.2 on 2026-02-11 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_siteimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('notification_email', models.EmailField(blank=True, help_text='Where to send submissions. Falls back to SiteSettings.contact_email.', max_length=254, verbose_name='Notification Email')),
                ('fields_schema', models.JSONField(blank=True, default=list, help_text='[{"name": "email", "type": "email", "label": "Email", "required": true}]', verbose_name='Fields Schema')),
                ('success_message_i18n', models.JSONField(blank=True, default=dict, help_text='{"pt": "Obrigado!", "en": "Thank you!"}', verbose_name='Success Message')),
                ('send_confirmation_email', models.BooleanField(default=False, verbose_name='Send Confirmation Email')),
                ('confirmation_subject_i18n', models.JSONField(blank=True, default=dict, help_text='Auto-reply subject per language', verbose_name='Confirmation Subject')),
                ('confirmation_body_i18n', models.JSONField(blank=True, default=dict, help_text='Auto-reply body per language', verbose_name='Confirmation Body')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Dynamic Form',
                'verbose_name_plural': 'Dynamic Forms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Submitted Data')),
                ('language', models.CharField(blank=True, default='', max_length=10, verbose_name='Language')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.dynamicform')),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.page')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
