# Generated by Django 6.0.2 on 2026-03-04 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0038_populate_i18n_html_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('version_number', models.IntegerField()),
                ('snapshot', models.JSONField(default=dict, help_text='Snapshot of versioned fields: {field_name: value}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Version',
                'verbose_name_plural': 'Content Versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_conten_content_16bd28_idx')],
                'unique_together': {('content_type', 'object_id', 'version_number')},
            },
        ),
    ]
