# Generated by Django 6.0.2 on 2026-03-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_contentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage',
            field=models.ForeignKey(blank=True, help_text="Page to use as the site front page. If not set, defaults to the page with slug 'home'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.page'),
        ),
    ]
