"""
Chat V3 Models

Database models for the V3 agentic chat architecture.
Handles plan persistence, step tracking, and memory management.
"""

from django.db import models
from django.conf import settings
from django.utils import timezone

from Core.models import BaseModel


class V3Plan(BaseModel):
    """
    Execution plan for a complex task.

    Plans are:
    - Generated by the LLM when a task requires multiple steps
    - Stored for persistence across page refreshes
    - Visible to users for transparency
    - Adaptable during execution
    """

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('cancelled', 'Cancelled'),
        ('adapted', 'Adapted'),  # Plan was modified during execution
    ]

    conversation = models.ForeignKey(
        'chat.Conversation',
        on_delete=models.CASCADE,
        related_name='v3_plans'
    )

    # Plan definition
    goal = models.TextField(
        help_text="What the user wants to achieve"
    )
    original_request = models.TextField(
        blank=True,
        help_text="The original user message that triggered this plan"
    )

    # Execution state
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending'
    )
    current_step_index = models.PositiveIntegerField(
        default=0,
        help_text="Index of the step currently being executed (0-indexed)"
    )

    # Discoveries and context built during execution
    discoveries = models.JSONField(
        default=dict,
        blank=True,
        help_text="Key facts discovered during execution (e.g., project IDs found)"
    )

    # Adaptation tracking
    adaptations = models.JSONField(
        default=list,
        blank=True,
        help_text="Record of plan modifications during execution"
    )
    adaptation_count = models.PositiveIntegerField(
        default=0,
        help_text="Number of times the plan was adapted"
    )

    # Timing
    started_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When plan execution started"
    )
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When plan execution completed"
    )

    # Metrics
    total_iterations = models.PositiveIntegerField(
        default=0,
        help_text="Total LLM iterations used"
    )
    total_tokens = models.PositiveIntegerField(
        default=0,
        help_text="Total tokens consumed"
    )

    class Meta:
        db_table = 'chat_v3_plans'
        ordering = ['-created_at']
        verbose_name = 'V3 Plan'
        verbose_name_plural = 'V3 Plans'
        indexes = [
            models.Index(fields=['conversation', 'status']),
            models.Index(fields=['status', 'created_at']),
        ]

    def __str__(self):
        step_count = self.steps.count()
        return f"Plan: {self.goal[:50]}... ({self.status}, {step_count} steps)"

    # =========================================================================
    # Status Management
    # =========================================================================

    def start(self):
        """Mark plan as started."""
        self.status = 'in_progress'
        self.started_at = timezone.now()
        self.save(update_fields=['status', 'started_at', 'updated_at'])

    def complete(self):
        """Mark plan as completed."""
        self.status = 'completed'
        self.completed_at = timezone.now()
        self.save(update_fields=['status', 'completed_at', 'updated_at'])

    def fail(self, reason: str = ""):
        """Mark plan as failed."""
        self.status = 'failed'
        self.completed_at = timezone.now()
        if reason:
            self.add_adaptation(f"Plan failed: {reason}")
        self.save(update_fields=['status', 'completed_at', 'adaptations', 'updated_at'])

    def cancel(self, reason: str = ""):
        """Mark plan as cancelled."""
        self.status = 'cancelled'
        self.completed_at = timezone.now()
        if reason:
            self.add_adaptation(f"Plan cancelled: {reason}")
        self.save(update_fields=['status', 'completed_at', 'adaptations', 'updated_at'])

    # =========================================================================
    # Step Management
    # =========================================================================

    def get_current_step(self):
        """Get the current step being executed."""
        return self.steps.filter(order=self.current_step_index).first()

    def get_next_pending_step(self):
        """Get the next step that needs to be executed."""
        return self.steps.filter(
            status='pending',
            order__gte=self.current_step_index
        ).order_by('order').first()

    def advance_to_next_step(self):
        """Move to the next step."""
        next_step = self.steps.filter(
            order__gt=self.current_step_index
        ).order_by('order').first()

        if next_step:
            self.current_step_index = next_step.order
            self.save(update_fields=['current_step_index', 'updated_at'])
            return next_step
        else:
            # No more steps
            if self.all_steps_complete():
                self.complete()
            return None

    def all_steps_complete(self) -> bool:
        """Check if all steps are done."""
        return not self.steps.exclude(
            status__in=['completed', 'skipped']
        ).exists()

    def get_completed_steps(self):
        """Get all completed steps."""
        return self.steps.filter(status='completed').order_by('order')

    def get_failed_steps(self):
        """Get all failed steps."""
        return self.steps.filter(status='failed').order_by('order')

    # =========================================================================
    # Adaptation
    # =========================================================================

    def add_adaptation(self, reason: str, new_steps: list = None):
        """
        Record a plan adaptation.

        Args:
            reason: Why the plan was adapted
            new_steps: Optional list of new step definitions to add
        """
        adaptation = {
            'at_step': self.current_step_index,
            'reason': reason,
            'timestamp': timezone.now().isoformat(),
            'new_steps_added': len(new_steps) if new_steps else 0,
        }
        self.adaptations.append(adaptation)
        self.adaptation_count += 1

        if new_steps:
            # Insert new steps after current position
            self._insert_steps(new_steps)

        self.status = 'adapted'
        self.save()

    def _insert_steps(self, step_definitions: list):
        """Insert new steps after the current step."""
        # Shift existing steps
        subsequent_steps = self.steps.filter(order__gt=self.current_step_index)
        shift_amount = len(step_definitions)

        for step in subsequent_steps.order_by('-order'):
            step.order += shift_amount
            step.save(update_fields=['order'])

        # Create new steps
        for i, step_def in enumerate(step_definitions):
            V3PlanStep.objects.create(
                plan=self,
                order=self.current_step_index + 1 + i,
                description=step_def.get('description', f'Step {i + 1}'),
                action_type=step_def.get('action_type', 'unknown'),
                expected_tool=step_def.get('tool', ''),
                expected_params=step_def.get('params', {}),
            )

    # =========================================================================
    # Discovery Management
    # =========================================================================

    def add_discovery(self, key: str, value):
        """Add a discovery to the plan context."""
        self.discoveries[key] = value
        self.save(update_fields=['discoveries', 'updated_at'])

    def get_discovery(self, key: str, default=None):
        """Get a discovery by key."""
        return self.discoveries.get(key, default)

    # =========================================================================
    # Serialization
    # =========================================================================

    def to_context_string(self) -> str:
        """Format plan for LLM context."""
        lines = [
            "## Current Plan",
            f"**Goal:** {self.goal}",
            f"**Status:** {self.status}",
            "",
            "### Steps"
        ]

        for step in self.steps.order_by('order'):
            if step.status == 'completed':
                status_icon = "[x]"
            elif step.status == 'in_progress':
                status_icon = "[>]"
            elif step.status == 'failed':
                status_icon = "[!]"
            elif step.status == 'skipped':
                status_icon = "[-]"
            else:
                status_icon = "[ ]"

            lines.append(f"{status_icon} {step.order + 1}. {step.description}")

            if step.result_summary:
                lines.append(f"    Result: {step.result_summary}")
            elif step.error:
                lines.append(f"    Error: {step.error}")

        if self.discoveries:
            lines.append("")
            lines.append("### Discoveries")
            for key, value in self.discoveries.items():
                lines.append(f"- {key}: {value}")

        return "\n".join(lines)

    def to_dataclass(self):
        """Convert to the dataclass Plan type for use in AgentLoop."""
        from .types import Plan as PlanDataclass, PlanStep as PlanStepDataclass
        from .config import PlanStatus, StepStatus

        status_map = {
            'pending': PlanStatus.PENDING,
            'in_progress': PlanStatus.IN_PROGRESS,
            'completed': PlanStatus.COMPLETED,
            'failed': PlanStatus.FAILED,
            'cancelled': PlanStatus.CANCELLED,
            'adapted': PlanStatus.IN_PROGRESS,
        }

        step_status_map = {
            'pending': StepStatus.PENDING,
            'in_progress': StepStatus.IN_PROGRESS,
            'completed': StepStatus.COMPLETED,
            'failed': StepStatus.FAILED,
            'skipped': StepStatus.SKIPPED,
        }

        steps = []
        for step in self.steps.order_by('order'):
            steps.append(PlanStepDataclass(
                index=step.order,
                description=step.description,
                action_type=step.action_type,
                status=step_status_map.get(step.status, StepStatus.PENDING),
                result_summary=step.result_summary,
                result_data=step.result_data,
                error=step.error,
                started_at=step.started_at,
                completed_at=step.completed_at,
            ))

        return PlanDataclass(
            goal=self.goal,
            steps=steps,
            status=status_map.get(self.status, PlanStatus.PENDING),
            current_step=self.current_step_index,
            discoveries=self.discoveries,
            created_at=self.created_at,
        )


class V3PlanStep(BaseModel):
    """
    Individual step in a V3 execution plan.

    Steps are:
    - Created when a plan is generated
    - Executed one at a time by the agent loop
    - Tracked for success/failure
    - Can be adapted during execution
    """

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('skipped', 'Skipped'),
    ]

    ACTION_TYPES = [
        ('search', 'Search'),
        ('create', 'Create'),
        ('update', 'Update'),
        ('delete', 'Delete'),
        ('move', 'Move'),
        ('complete', 'Complete'),
        ('archive', 'Archive'),
        ('other', 'Other'),
    ]

    plan = models.ForeignKey(
        V3Plan,
        on_delete=models.CASCADE,
        related_name='steps'
    )

    # Step definition
    order = models.PositiveIntegerField(
        help_text="Step order (0-indexed)"
    )
    description = models.TextField(
        help_text="Human-readable step description"
    )
    action_type = models.CharField(
        max_length=20,
        choices=ACTION_TYPES,
        default='other',
        help_text="Type of action this step performs"
    )

    # Expected execution (from plan generation)
    expected_tool = models.CharField(
        max_length=50,
        blank=True,
        help_text="Expected tool to be called (search or execute)"
    )
    expected_params = models.JSONField(
        default=dict,
        blank=True,
        help_text="Expected parameters for the tool call"
    )

    # Actual execution
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending'
    )
    actual_tool = models.CharField(
        max_length=50,
        blank=True,
        help_text="Tool that was actually called"
    )
    actual_params = models.JSONField(
        default=dict,
        blank=True,
        help_text="Parameters that were actually used"
    )

    # Results
    result_summary = models.TextField(
        blank=True,
        help_text="Summary of the step result"
    )
    result_data = models.JSONField(
        null=True,
        blank=True,
        help_text="Full result data from execution"
    )
    error = models.TextField(
        blank=True,
        help_text="Error message if step failed"
    )

    # Timing
    started_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When step execution started"
    )
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When step execution completed"
    )

    # Iterations used for this step
    iterations_used = models.PositiveIntegerField(
        default=0,
        help_text="Number of agent loop iterations used for this step"
    )

    class Meta:
        db_table = 'chat_v3_plan_steps'
        ordering = ['plan', 'order']
        unique_together = [['plan', 'order']]
        verbose_name = 'V3 Plan Step'
        verbose_name_plural = 'V3 Plan Steps'
        indexes = [
            models.Index(fields=['plan', 'status']),
        ]

    def __str__(self):
        return f"Step {self.order + 1}: {self.description[:40]}... ({self.status})"

    # =========================================================================
    # Status Management
    # =========================================================================

    def start(self):
        """Mark step as in progress."""
        self.status = 'in_progress'
        self.started_at = timezone.now()
        self.save(update_fields=['status', 'started_at', 'updated_at'])

    def complete(self, summary: str, data: dict = None):
        """Mark step as completed."""
        self.status = 'completed'
        self.result_summary = summary
        self.result_data = data
        self.completed_at = timezone.now()
        self.save(update_fields=[
            'status', 'result_summary', 'result_data',
            'completed_at', 'updated_at'
        ])

    def fail(self, error: str):
        """Mark step as failed."""
        self.status = 'failed'
        self.error = error
        self.completed_at = timezone.now()
        self.save(update_fields=['status', 'error', 'completed_at', 'updated_at'])

    def skip(self, reason: str = ""):
        """Mark step as skipped."""
        self.status = 'skipped'
        if reason:
            self.error = f"Skipped: {reason}"
        self.completed_at = timezone.now()
        self.save(update_fields=['status', 'error', 'completed_at', 'updated_at'])

    def record_execution(self, tool: str, params: dict):
        """Record what was actually executed."""
        self.actual_tool = tool
        self.actual_params = params
        self.iterations_used += 1
        self.save(update_fields=['actual_tool', 'actual_params', 'iterations_used', 'updated_at'])

    # =========================================================================
    # Properties
    # =========================================================================

    @property
    def duration_ms(self) -> int | None:
        """Get execution duration in milliseconds."""
        if self.started_at and self.completed_at:
            delta = self.completed_at - self.started_at
            return int(delta.total_seconds() * 1000)
        return None

    @property
    def is_complete(self) -> bool:
        """Check if step is done (success or failure)."""
        return self.status in ('completed', 'failed', 'skipped')

    @property
    def is_successful(self) -> bool:
        """Check if step completed successfully."""
        return self.status == 'completed'


class V3Memory(BaseModel):
    """
    Working memory for a V3 conversation.

    Stores:
    - Current discoveries from tool calls
    - Learnings extracted from interactions
    - User preferences observed
    - Context for the active task
    """

    conversation = models.OneToOneField(
        'chat.Conversation',
        on_delete=models.CASCADE,
        related_name='v3_memory'
    )

    # Current task context
    active_plan = models.ForeignKey(
        V3Plan,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='memory_references',
        help_text="Currently active plan being executed"
    )
    current_goal = models.TextField(
        blank=True,
        help_text="Current task goal (may exist without a plan)"
    )

    # Working memory (session-scoped)
    discoveries = models.JSONField(
        default=list,
        blank=True,
        help_text="Recent discoveries from tool calls"
    )
    context_items = models.JSONField(
        default=dict,
        blank=True,
        help_text="Key items discovered (project IDs, task IDs, etc.)"
    )

    # Learnings (longer-lived)
    learnings = models.JSONField(
        default=list,
        blank=True,
        help_text="Insights extracted from interactions"
    )
    failed_approaches = models.JSONField(
        default=list,
        blank=True,
        help_text="Approaches that didn't work"
    )

    # User preferences (persistent)
    preferred_containers = models.JSONField(
        default=dict,
        blank=True,
        help_text="Preferred containers for different resource types"
    )
    common_tags = models.JSONField(
        default=list,
        blank=True,
        help_text="Commonly used tags"
    )

    class Meta:
        db_table = 'chat_v3_memory'
        verbose_name = 'V3 Memory'
        verbose_name_plural = 'V3 Memories'

    def __str__(self):
        return f"Memory for Conv #{self.conversation_id}"

    # =========================================================================
    # Discovery Management
    # =========================================================================

    def add_discovery(self, tool: str, query: dict, result_summary: str, result_data=None):
        """Add a discovery from a tool call."""
        discovery = {
            'tool': tool,
            'query': query,
            'summary': result_summary,
            'data': result_data,
            'timestamp': timezone.now().isoformat(),
        }
        self.discoveries.append(discovery)

        # Keep last 20 discoveries
        if len(self.discoveries) > 20:
            self.discoveries = self.discoveries[-20:]

        self.save(update_fields=['discoveries', 'updated_at'])

    def add_context_item(self, key: str, value):
        """Add a key context item (e.g., found project ID)."""
        self.context_items[key] = value
        self.save(update_fields=['context_items', 'updated_at'])

    def get_recent_discoveries(self, limit: int = 5) -> list:
        """Get recent discoveries."""
        return self.discoveries[-limit:] if self.discoveries else []

    # =========================================================================
    # Learning Management
    # =========================================================================

    def add_learning(self, learning: str, learning_type: str = 'insight'):
        """Add a learning."""
        self.learnings.append({
            'type': learning_type,
            'content': learning,
            'timestamp': timezone.now().isoformat(),
        })

        # Keep last 50 learnings
        if len(self.learnings) > 50:
            self.learnings = self.learnings[-50:]

        self.save(update_fields=['learnings', 'updated_at'])

    def add_failed_approach(self, approach: str, error: str):
        """Record a failed approach."""
        self.failed_approaches.append({
            'approach': approach,
            'error': error,
            'timestamp': timezone.now().isoformat(),
        })

        # Keep last 20 failed approaches
        if len(self.failed_approaches) > 20:
            self.failed_approaches = self.failed_approaches[-20:]

        self.save(update_fields=['failed_approaches', 'updated_at'])

    # =========================================================================
    # Preference Management
    # =========================================================================

    def set_preferred_container(self, resource_type: str, container_type: str, container_id: int):
        """Set a preferred container for a resource type."""
        self.preferred_containers[resource_type] = {
            'container_type': container_type,
            'container_id': container_id,
        }
        self.save(update_fields=['preferred_containers', 'updated_at'])

    def get_preferred_container(self, resource_type: str) -> dict | None:
        """Get the preferred container for a resource type."""
        return self.preferred_containers.get(resource_type)

    def add_common_tag(self, tag: str):
        """Track a commonly used tag."""
        if tag not in self.common_tags:
            self.common_tags.append(tag)
            # Keep last 20 tags
            if len(self.common_tags) > 20:
                self.common_tags = self.common_tags[-20:]
            self.save(update_fields=['common_tags', 'updated_at'])

    # =========================================================================
    # Context Building
    # =========================================================================

    def to_context_string(self) -> str:
        """Format memory for LLM context."""
        lines = []

        # Recent discoveries
        recent = self.get_recent_discoveries(5)
        if recent:
            lines.append("## Working Memory (recent discoveries)")
            for d in recent:
                lines.append(f"- {d['summary']}")

        # Key context items
        if self.context_items:
            lines.append("")
            lines.append("## Context")
            for key, value in self.context_items.items():
                lines.append(f"- {key}: {value}")

        # Failed approaches (to avoid repeating)
        if self.failed_approaches:
            lines.append("")
            lines.append("## Avoid (previously failed)")
            for fa in self.failed_approaches[-3:]:
                lines.append(f"- {fa['approach']}")

        return "\n".join(lines) if lines else ""

    # =========================================================================
    # State Management
    # =========================================================================

    def clear_working_memory(self):
        """Clear session-scoped memory."""
        self.discoveries = []
        self.context_items = {}
        self.current_goal = ""
        self.active_plan = None
        self.save(update_fields=[
            'discoveries', 'context_items', 'current_goal',
            'active_plan', 'updated_at'
        ])

    def clear_all(self):
        """Clear all memory (new conversation)."""
        self.clear_working_memory()
        self.learnings = []
        self.failed_approaches = []
        self.preferred_containers = {}
        self.common_tags = []
        self.save()
