# Generated by Django 5.2.6 on 2025-12-04 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Auto-generated or user-set conversation title', max_length=200)),
                ('context_type', models.CharField(choices=[('general', 'General'), ('project', 'Project'), ('area', 'Area')], default='general', max_length=20)),
                ('context_id', models.PositiveIntegerField(blank=True, help_text='ID of the linked Project or Area', null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('model_name', models.CharField(default='gemini-flash', help_text='LLM model used for this conversation', max_length=50)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text="Tokens used for this message's prompt")),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Tokens in the response (for assistant messages)')),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Time taken to generate response', null=True)),
                ('has_vel_commands', models.BooleanField(default=False)),
                ('vel_session_id', models.CharField(blank=True, help_text='VEL session ID for audit linking', max_length=64)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatVELExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('denied', 'Denied'), ('timeout', 'Timeout'), ('confirmation_required', 'Confirmation Required'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=25)),
                ('result_summary', models.TextField(blank=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(blank=True, max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vel_executions', to='chat.message')),
            ],
            options={
                'db_table': 'chat_vel_executions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_archived'], name='chat_conver_user_id_d5e8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'last_message_at'], name='chat_conver_user_id_9a7881_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['context_type', 'context_id'], name='chat_conver_context_5241e9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='chat_messag_role_ddd811_idx'),
        ),
        migrations.AddIndex(
            model_name='chatvelexecution',
            index=models.Index(fields=['message', 'action'], name='chat_vel_ex_message_9fca19_idx'),
        ),
        migrations.AddIndex(
            model_name='chatvelexecution',
            index=models.Index(fields=['confirmation_token'], name='chat_vel_ex_confirm_1980be_idx'),
        ),
    ]
