# Generated by Django 5.2.6 on 2025-12-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_result_data_to_vel_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='use_v2',
            field=models.BooleanField(default=False, help_text='Use V2 chat architecture (DIRECT/AGENTIC/CLARIFY routing)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='v2_enabled_at',
            field=models.DateTimeField(blank=True, help_text='When V2 was enabled for this conversation', null=True),
        ),
    ]
