# Generated by Django 5.2.6 on 2025-12-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_v2_architecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_goal', models.TextField(blank=True, help_text='What the user wants to achieve')),
                ('route_type', models.CharField(blank=True, help_text='DIRECT, AGENTIC, or CLARIFY', max_length=20)),
                ('current_stage', models.PositiveIntegerField(default=0, help_text='Current step being executed (1-indexed)')),
                ('total_stages', models.PositiveIntegerField(default=0, help_text='Total steps in the plan')),
                ('plan_state', models.JSONField(blank=True, default=dict, help_text='Plan steps, tool params, intermediate data')),
                ('stage_results', models.JSONField(blank=True, default=dict, help_text='Results from each completed stage (keyed by stage number)')),
                ('failed_approaches', models.JSONField(blank=True, default=list, help_text="Approaches that didn't work - avoid repeating")),
                ('key_learnings', models.JSONField(blank=True, default=list, help_text='Insights discovered during execution')),
                ('pending_clarification', models.JSONField(blank=True, default=dict, help_text='Question asked, options provided, context for clarification')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memory', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Agent Memory',
                'verbose_name_plural': 'Agent Memories',
                'db_table': 'chat_agent_memory',
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(help_text='Step order (1-indexed)')),
                ('description', models.TextField(help_text='Human-readable step description')),
                ('tool', models.CharField(help_text='Tool name: data_tool or execute_tool', max_length=50)),
                ('action', models.CharField(help_text='Action: search, list, read, create, update, delete, etc.', max_length=50)),
                ('resource_type', models.CharField(blank=True, help_text='Resource type: note, task, project, area, tag', max_length=50)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Parameters for the tool action')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, help_text='Result data from successful execution', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('started_at', models.DateTimeField(blank=True, help_text='When execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution completed (success or failure)', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.PositiveIntegerField(default=2, help_text='Maximum retry attempts allowed')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='chat.agentmemory')),
            ],
            options={
                'verbose_name': 'Plan Step',
                'verbose_name_plural': 'Plan Steps',
                'db_table': 'chat_plan_steps',
                'ordering': ['memory', 'order'],
                'unique_together': {('memory', 'order')},
            },
        ),
    ]
