# Generated by Django 5.2.6 on 2025-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_agent_memory_and_plan_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='use_v2',
            field=models.BooleanField(default=True, help_text='Use V2 chat architecture (DIRECT/AGENTIC/CLARIFY routing)'),
        ),
        migrations.AlterField(
            model_name='planstep',
            name='tool',
            field=models.CharField(help_text='Tool name: search_tool or execute_tool', max_length=50),
        ),
    ]
