# Generated by Django 5.2.6 on 2025-12-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_use_v2_alter_planstep_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_version',
            field=models.CharField(choices=[('v1', 'V1 - Original'), ('v2', 'V2 - DIRECT/AGENTIC'), ('v3', 'V3 - Agentic Loop')], default='v2', help_text='Chat architecture version to use', max_length=10),
        ),
    ]
