# Generated by Django 5.2.6 on 2025-12-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_chat_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.TextField(help_text='What the user wants to achieve')),
                ('original_request', models.TextField(blank=True, help_text='The original user message that triggered this plan')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('adapted', 'Adapted')], default='pending', max_length=20)),
                ('current_step_index', models.PositiveIntegerField(default=0, help_text='Index of the step currently being executed (0-indexed)')),
                ('discoveries', models.JSONField(blank=True, default=dict, help_text='Key facts discovered during execution (e.g., project IDs found)')),
                ('adaptations', models.JSONField(blank=True, default=list, help_text='Record of plan modifications during execution')),
                ('adaptation_count', models.PositiveIntegerField(default=0, help_text='Number of times the plan was adapted')),
                ('started_at', models.DateTimeField(blank=True, help_text='When plan execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When plan execution completed', null=True)),
                ('total_iterations', models.PositiveIntegerField(default=0, help_text='Total LLM iterations used')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total tokens consumed')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v3_plans', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'V3 Plan',
                'verbose_name_plural': 'V3 Plans',
                'db_table': 'chat_v3_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='V3Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_goal', models.TextField(blank=True, help_text='Current task goal (may exist without a plan)')),
                ('discoveries', models.JSONField(blank=True, default=list, help_text='Recent discoveries from tool calls')),
                ('context_items', models.JSONField(blank=True, default=dict, help_text='Key items discovered (project IDs, task IDs, etc.)')),
                ('learnings', models.JSONField(blank=True, default=list, help_text='Insights extracted from interactions')),
                ('failed_approaches', models.JSONField(blank=True, default=list, help_text="Approaches that didn't work")),
                ('preferred_containers', models.JSONField(blank=True, default=dict, help_text='Preferred containers for different resource types')),
                ('common_tags', models.JSONField(blank=True, default=list, help_text='Commonly used tags')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='v3_memory', to='chat.conversation')),
                ('active_plan', models.ForeignKey(blank=True, help_text='Currently active plan being executed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_references', to='chat.v3plan')),
            ],
            options={
                'verbose_name': 'V3 Memory',
                'verbose_name_plural': 'V3 Memories',
                'db_table': 'chat_v3_memory',
            },
        ),
        migrations.CreateModel(
            name='V3PlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(help_text='Step order (0-indexed)')),
                ('description', models.TextField(help_text='Human-readable step description')),
                ('action_type', models.CharField(choices=[('search', 'Search'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('move', 'Move'), ('complete', 'Complete'), ('archive', 'Archive'), ('other', 'Other')], default='other', help_text='Type of action this step performs', max_length=20)),
                ('expected_tool', models.CharField(blank=True, help_text='Expected tool to be called (search or execute)', max_length=50)),
                ('expected_params', models.JSONField(blank=True, default=dict, help_text='Expected parameters for the tool call')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('actual_tool', models.CharField(blank=True, help_text='Tool that was actually called', max_length=50)),
                ('actual_params', models.JSONField(blank=True, default=dict, help_text='Parameters that were actually used')),
                ('result_summary', models.TextField(blank=True, help_text='Summary of the step result')),
                ('result_data', models.JSONField(blank=True, help_text='Full result data from execution', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if step failed')),
                ('started_at', models.DateTimeField(blank=True, help_text='When step execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When step execution completed', null=True)),
                ('iterations_used', models.PositiveIntegerField(default=0, help_text='Number of agent loop iterations used for this step')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='chat.v3plan')),
            ],
            options={
                'verbose_name': 'V3 Plan Step',
                'verbose_name_plural': 'V3 Plan Steps',
                'db_table': 'chat_v3_plan_steps',
                'ordering': ['plan', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='v3plan',
            index=models.Index(fields=['conversation', 'status'], name='chat_v3_pla_convers_bcaf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='v3plan',
            index=models.Index(fields=['status', 'created_at'], name='chat_v3_pla_status_33593b_idx'),
        ),
        migrations.AddIndex(
            model_name='v3planstep',
            index=models.Index(fields=['plan', 'status'], name='chat_v3_pla_plan_id_6028c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='v3planstep',
            unique_together={('plan', 'order')},
        ),
    ]
