# Generated by Django 5.2.6 on 2025-12-18 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_v3_planning_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_version',
            field=models.CharField(choices=[('v1', 'V1 - Original'), ('v2', 'V2 - DIRECT/AGENTIC'), ('v3', 'V3 - Agentic Loop'), ('v4', 'V4 - Multi-Agent')], default='v2', help_text='Chat architecture version to use', max_length=10),
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', help_text='Running summary of conversation topics and actions')),
                ('topics', models.JSONField(blank=True, default=list, help_text="List of topics discussed: ['inbox', 'tasks', 'para']")),
                ('mentioned_entities', models.JSONField(blank=True, default=dict, help_text="Entities mentioned in conversation: {'task': [1,2,3], 'project': [5]}")),
                ('last_created_entities', models.JSONField(blank=True, default=dict, help_text="Most recent entity created per type: {'task': 42}")),
                ('last_affected_entities', models.JSONField(blank=True, default=dict, help_text="Entities affected by last execution: {'task': [1,2,3]}")),
                ('active_execution_id', models.CharField(blank=True, help_text='UUID of execution currently awaiting user response', max_length=36, null=True)),
                ('last_execution_summary', models.JSONField(blank=True, help_text='Summary of the last completed execution', null=True)),
                ('message_count', models.IntegerField(default=0, help_text='Total messages in this conversation')),
                ('total_executions', models.IntegerField(default=0, help_text='Total executions performed in this conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(help_text='The conversation this state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='v4_state', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'V4 Conversation State',
                'verbose_name_plural': 'V4 Conversation States',
                'db_table': 'chat_v4_conversation_state',
            },
        ),
    ]
