# Generated by Django 5.2.6 on 2025-12-19 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_v4_conversation_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStateRecord',
            fields=[
                ('execution_id', models.CharField(help_text='UUID of this execution', max_length=36, primary_key=True, serialize=False)),
                ('state_data', models.JSONField(help_text='Full serialized ExecutionState object')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('executing', 'Executing'), ('awaiting_user', 'Awaiting User'), ('completing', 'Completing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='planning', help_text='Current execution status', max_length=20)),
                ('user_request', models.TextField(help_text='The original user request')),
                ('step_count', models.IntegerField(default=0, help_text='Total number of steps in the plan')),
                ('steps_completed', models.IntegerField(default=0, help_text='Number of steps completed')),
                ('has_errors', models.BooleanField(default=False, help_text='Whether any errors occurred')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used in this execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution completed (success or failure)', null=True)),
                ('conversation', models.ForeignKey(help_text='The conversation this execution belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='v4_executions', to='chat.conversation')),
                ('user', models.ForeignKey(help_text='The user who initiated this execution', on_delete=django.db.models.deletion.CASCADE, related_name='v4_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'V4 Execution State',
                'verbose_name_plural': 'V4 Execution States',
                'db_table': 'chat_v4_execution_state',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'status'], name='chat_v4_exe_convers_c87a6e_idx'), models.Index(fields=['user', 'created_at'], name='chat_v4_exe_user_id_b6ea70_idx'), models.Index(fields=['status', 'created_at'], name='chat_v4_exe_status_a42110_idx')],
            },
        ),
    ]
