# Generated by Django 5.2.6 on 2025-12-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_add_execution_state_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_version',
            field=models.CharField(choices=[('v1', 'V1 - Monolithic'), ('v2', 'V2 - DIRECT/AGENTIC'), ('v3', 'V3 - Agentic Loop'), ('v4', 'V4 - Multi-Agent')], default='v1', help_text='Chat architecture version to use', max_length=10),
        ),
    ]
