# Generated by Django 5.1.1 on 2025-10-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, help_text='e.g., "Sports scholarship agency for student athletes"', max_length=200, verbose_name='Industry')),
                ('brand_personality', models.TextField(blank=True, help_text='Describe brand character. e.g., "Professional, inspiring, trustworthy, youth-oriented"', verbose_name='Brand Personality')),
                ('design_guidelines', models.TextField(blank=True, help_text='Design rules and preferences. e.g., "Use full-width hero sections, bold typography, gradient overlays on images"', verbose_name='Design Guidelines')),
                ('tone_of_voice', models.TextField(blank=True, help_text='How content should sound. e.g., "Professional but approachable, inspiring, action-oriented"', verbose_name='Tone of Voice')),
                ('key_messages', models.TextField(blank=True, help_text='Core messages to communicate (one per line)', verbose_name='Key Messages')),
                ('content_guidelines', models.TextField(blank=True, help_text='What to include/avoid in content. e.g., "Use statistics, avoid clichés, be transparent"', verbose_name='Content Guidelines')),
                ('seo_keywords_pt', models.TextField(blank=True, help_text='Comma-separated. e.g., "bolsas de estudo, atletas, USA"', verbose_name='SEO Keywords (PT)')),
                ('seo_keywords_en', models.TextField(blank=True, help_text='Comma-separated. e.g., "sports scholarships, athletes, USA"', verbose_name='SEO Keywords (EN)')),
                ('reference_websites', models.TextField(blank=True, help_text='URLs of good design examples (one per line)', verbose_name='Reference Websites')),
                ('html_examples', models.TextField(blank=True, help_text='HTML snippets the LLM can use as reference', verbose_name='HTML Examples')),
                ('design_model', models.CharField(choices=[('claude', 'Claude Sonnet 4.5'), ('gpt-5', 'GPT-5'), ('gemini-pro', 'Gemini Pro')], default='claude', max_length=30, verbose_name='Design Model')),
                ('content_model', models.CharField(choices=[('gemini-flash', 'Gemini Flash'), ('gemini-pro', 'Gemini Pro'), ('claude', 'Claude Sonnet 4.5')], default='gemini-flash', max_length=30, verbose_name='Content Model')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Generation Settings',
                'verbose_name_plural': 'AI Generation Settings',
            },
        ),
        migrations.RemoveField(
            model_name='designreference',
            name='context',
        ),
        migrations.AlterModelOptions(
            name='designreference',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Design Reference', 'verbose_name_plural': 'Design References'},
        ),
        migrations.DeleteModel(
            name='GenerationContext',
        ),
    ]
