# Generated by Django 5.1.1 on 2025-10-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aigenerationsettings_remove_designreference_context_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIGenerationSettings',
        ),
        migrations.DeleteModel(
            name='DesignReference',
        ),
    ]
