# Generated by Django 6.0.2 on 2026-02-09 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_initial'),
        ('core', '0028_blueprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('generate_page', 'Generate Page'), ('refine_page', 'Refine Page'), ('chat_refine', 'Chat Refine'), ('refine_section', 'Refine Section'), ('refine_header', 'Refine Header'), ('refine_footer', 'Refine Footer'), ('templatize', 'Templatize'), ('generate_metadata', 'Generate Metadata'), ('analyze_images', 'Analyze Images'), ('analyze_bulk', 'Analyze Bulk Pages'), ('generate_design_guide', 'Generate Design Guide'), ('suggest_sections', 'Suggest Sections'), ('fill_section', 'Fill Section')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=20)),
                ('section_name', models.CharField(blank=True, default='', max_length=100)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('user_prompt', models.TextField(blank=True, default='')),
                ('response_text', models.TextField(blank=True, default='')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_call_logs', to='core.page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
