# Generated by Django 6.0.2 on 2026-03-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aicalllog_routing_ms_aicalllog_routing_tier_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0038_populate_i18n_html_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinementsession',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='refinementsession',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refinementsession',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refinement_sessions', to='core.page'),
        ),
    ]
