# Generated by Django 6.1.1 on 2026-10-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_designconsistencyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicalllog',
            name='action',
            field=models.CharField(choices=[('generate_page', 'Generate Page'), ('refine_page', 'Refine Page'), ('chat_refine', 'Chat Refine'), ('refine_section', 'Refine Section'), ('refine_header', 'Refine Header'), ('refine_footer', 'Refine Footer'), ('templatize', 'Templatize'), ('generate_metadata', 'Generate Metadata'), ('analyze_images', 'Analyze Images'), ('analyze_bulk', 'Analyze Bulk Pages'), ('generate_design_guide', 'Generate Design Guide'), ('suggest_sections', 'Suggest Sections'), ('fill_section', 'Fill Section'), ('select_components', 'Select Components'), ('refine_element', 'Refine Element'), ('templatize_v2', 'Templatize V2'), ('refine_routing', 'Refine Routing')], max_length=50),
        ),
    ]
