"""
Django settings for get_algarve project.
Generated by Django Site Builder
"""

import environ
from pathlib import Path
from django.utils.translation import gettext_lazy as _
import warnings
import os

# Load environment variables
env = environ.Env()
env.read_env()

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment
ENVIRONMENT = env('ENVIRONMENT', default='development')

# Debug mode - can be overridden independently of environment
DEBUG_MODE = env('DEBUG_MODE', default='False') == 'True'

# Basic settings
SECRET_KEY = env('SECRET_KEY', default='django-insecure-372d0ca8799a3029769a1bc4297480e0df57630a1c11dbe9')

# Enable DEBUG if in development OR if DEBUG_MODE is explicitly enabled
DEBUG = ENVIRONMENT == 'development' or DEBUG_MODE

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*.railway.app']

# Site Configuration
SITE_NAME = "Get Algarve"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'anymail',
    'storages',
    'core',
]

# Add whitenoise.runserver_nostatic only in production
if ENVIRONMENT != 'development':
    INSTALLED_APPS.insert(0, 'whitenoise.runserver_nostatic')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # For language switching
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DomainMiddleware',
    'core.middleware.MaintenanceModeMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'core.context_processors.site_settings',
                'core.context_processors.site_images',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database - SQLite for both development and production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'pt'
LANGUAGES = [('pt', 'PT'), ('en', 'EN')]
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_STORAGE depending on environment
if ENVIRONMENT == 'development':
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
    warnings.warn("Running in DEVELOPMENT mode. collectstatic is NOT required.")
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files configuration
if ENVIRONMENT == 'development':
    # Local media files for development
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

    # Default STORAGES for development
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.StaticFilesStorage",
        },
    }
else:
    # Production environment - Security settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Check if Google Cloud Storage is configured
    if env('GS_BUCKET_NAME', default=''):
        # Google Cloud Storage configuration with domain-based folders
        from google.oauth2 import service_account
        import json

        GS_BUCKET_NAME = env('GS_BUCKET_NAME')
        GS_PROJECT_ID = env('GS_PROJECT_ID')

        # Set MEDIA_URL to GCS bucket
        MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'

        # Credentials setup - supports both file path and JSON string
        credentials_json = env('GCS_CREDENTIALS_JSON', default='')
        credentials_path = env('GS_CREDENTIALS_FILE_PATH', default='')

        if credentials_json:
            # Option 1: Load from environment variable JSON string (good for Railway/Heroku)
            GS_CREDENTIALS = service_account.Credentials.from_service_account_info(
                json.loads(credentials_json)
            )
        elif credentials_path:
            # Option 2: Load from file path (good for local development)
            GS_CREDENTIALS_FILE_PATH = BASE_DIR / credentials_path
            GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
                GS_CREDENTIALS_FILE_PATH
            )
        else:
            GS_CREDENTIALS = None

        GS_DEFAULT_ACL = None  # Use bucket's default ACL
        GS_FILE_OVERWRITE = False  # Don't overwrite files with same name
        GS_MAX_MEMORY_SIZE = 5242880  # 5MB - files larger than this use streaming
        GS_QUERYSTRING_AUTH = False  # Generate public URLs without authentication

        # Default domain fallback (used in management commands when no request context)
        CURRENT_DOMAIN = env('DEFAULT_DOMAIN', default='default')

        # Configure STORAGES for Django 4.2+
        STORAGES = {
            "default": {
                "BACKEND": "config.storage_backends.DomainBasedStorage",
            },
            "staticfiles": {
                "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
            },
        }

        # Keep for backward compatibility
        DEFAULT_FILE_STORAGE = 'config.storage_backends.DomainBasedStorage'
    else:
        # Fallback to local media storage if GCS not configured in production
        MEDIA_URL = '/media/'
        MEDIA_ROOT = BASE_DIR / 'media'

        STORAGES = {
            "default": {
                "BACKEND": "django.core.files.storage.FileSystemStorage",
            },
            "staticfiles": {
                "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
            },
        }

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'https://*.railway.app',
]

# Authentication URLs (Django default auth)
LOGIN_URL = '/backoffice/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email Configuration (Mailgun via Anymail)
if ENVIRONMENT == 'development':
    # Development: Print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production: Use Mailgun via Anymail
    EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
    ANYMAIL = {
        "MAILGUN_API_KEY": env('MAILGUN_API_KEY', default=''),
        "MAILGUN_API_URL": env('MAILGUN_API_URL', default='https://api.eu.mailgun.net/v3'),
    }

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@get_algarve.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
ENABLE_DEBUG_LOGGING = env('ENABLE_DEBUG_LOGGING', default='False') == 'True'

if DEBUG_MODE or ENABLE_DEBUG_LOGGING or ENVIRONMENT != 'development':
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': True,
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }

    # Debug information
    print("=" * 60)
    print("🔍 GET ALGARVE DEBUG INFO")
    print("=" * 60)
    print(f"🔍 ENVIRONMENT: {ENVIRONMENT}")
    print(f"🔍 DEBUG: {DEBUG}")
    print(f"🔍 DEBUG_MODE: {DEBUG_MODE}")
    print(f"🔍 STATIC_ROOT: {STATIC_ROOT}")
    print(f"🔍 MEDIA_URL: {MEDIA_URL}")
    if ENVIRONMENT != 'development':
        print(f"🔍 GS_BUCKET_NAME: {env('GS_BUCKET_NAME', default='Not set')}")
    print("=" * 60)
