# Generated by Django 5.1.1 on 2025-10-20 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_pt', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_pt', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('key', models.SlugField(blank=True, help_text='Optional unique identifier to reference this image in templates', unique=True, verbose_name='Key')),
                ('image', models.ImageField(upload_to='site_images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('alt_text_pt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text')),
                ('alt_text_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text')),
                ('category', models.CharField(choices=[('general', 'General'), ('project', 'Project'), ('news', 'News'), ('hero', 'Hero/Banner'), ('logo', 'Logo/Badge'), ('other', 'Other')], default='general', help_text='Category for organizing images', max_length=20, verbose_name='Category')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags for filtering (e.g., construction, villa, pool)', max_length=200, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Get Algarve', max_length=100, verbose_name='Site Name')),
                ('site_name_pt', models.CharField(default='Get Algarve', max_length=100, null=True, verbose_name='Site Name')),
                ('site_name_en', models.CharField(default='Get Algarve', max_length=100, null=True, verbose_name='Site Name')),
                ('site_description', models.CharField(blank=True, max_length=255, verbose_name='Site Description')),
                ('site_description_pt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Description')),
                ('site_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Logo')),
                ('contact_email', models.EmailField(default='geral@portugalwebdesign.pt', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(default='+351967764290', max_length=20, verbose_name='Contact Phone')),
                ('contact_address', models.TextField(blank=True, default='Rua do Indico Edf Altis R/c\r\nc', verbose_name='Address')),
                ('contact_address_pt', models.TextField(blank=True, default='Rua do Indico Edf Altis R/c\r\nc', null=True, verbose_name='Address')),
                ('contact_address_en', models.TextField(blank=True, default='Rua do Indico Edf Altis R/c\r\nc', null=True, verbose_name='Address')),
                ('tagline', models.CharField(default='Construímos os seus sonhos', help_text='Company tagline for footer', max_length=200, verbose_name='Tagline')),
                ('tagline_pt', models.CharField(default='Construímos os seus sonhos', help_text='Company tagline for footer', max_length=200, null=True, verbose_name='Tagline')),
                ('tagline_en', models.CharField(default='Construímos os seus sonhos', help_text='Company tagline for footer', max_length=200, null=True, verbose_name='Tagline')),
                ('phone_1', models.CharField(blank=True, default='(+351) 289 098 974', max_length=20, verbose_name='Phone 1')),
                ('phone_1_note', models.CharField(blank=True, default='*chamada de rede fixa local', max_length=100, verbose_name='Phone 1 Note')),
                ('phone_2', models.CharField(blank=True, default='(+351) 966 086 785', max_length=20, verbose_name='Phone 2')),
                ('phone_2_note', models.CharField(blank=True, max_length=100, verbose_name='Phone 2 Note')),
                ('phone_3', models.CharField(blank=True, default='(+351) 965 932 988', max_length=20, verbose_name='Phone 3')),
                ('phone_3_note', models.CharField(blank=True, default='*chamada de rede móvel local', max_length=100, verbose_name='Phone 3 Note')),
                ('footer_address', models.TextField(default='Rua General Humberto Delgado, lt 100,\nloja D 8365-173 Almacil Portugal', help_text='Full address for footer', verbose_name='Footer Address')),
                ('footer_address_pt', models.TextField(default='Rua General Humberto Delgado, lt 100,\nloja D 8365-173 Almacil Portugal', help_text='Full address for footer', null=True, verbose_name='Footer Address')),
                ('footer_address_en', models.TextField(default='Rua General Humberto Delgado, lt 100,\nloja D 8365-173 Almacil Portugal', help_text='Full address for footer', null=True, verbose_name='Footer Address')),
                ('pme_lider_badge', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='PME Líder Badge')),
                ('excelencia_badge', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Excelência Badge')),
                ('livro_reclamacoes_url', models.URLField(blank=True, help_text='Link to online complaints book', verbose_name='Livro de Reclamações URL')),
                ('website_by_text', models.CharField(blank=True, default='Portugal Web Design', max_length=100, verbose_name='Website By Text')),
                ('website_by_text_pt', models.CharField(blank=True, default='Portugal Web Design', max_length=100, null=True, verbose_name='Website By Text')),
                ('website_by_text_en', models.CharField(blank=True, default='Portugal Web Design', max_length=100, null=True, verbose_name='Website By Text')),
                ('website_by_url', models.URLField(blank=True, default='https://portugalwebdesign.pt', verbose_name='Website By URL')),
                ('google_maps_embed_url', models.TextField(blank=True, help_text='Full Google Maps embed iframe URL', verbose_name='Google Maps Embed URL')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='YouTube URL')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter URL')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('primary_color', models.CharField(default='#1e3a8a', help_text='Hex color code (e.g., #1e3a8a for navy blue)', max_length=7, verbose_name='Primary Color')),
                ('primary_color_hover', models.CharField(default='#1e40af', help_text='Hover state for primary color', max_length=7, verbose_name='Primary Color Hover')),
                ('secondary_color', models.CharField(default='#64748b', help_text='Secondary/accent color', max_length=7, verbose_name='Secondary Color')),
                ('text_color', models.CharField(default='#1f2937', help_text='Main text color', max_length=7, verbose_name='Text Color')),
                ('heading_color', models.CharField(default='#111827', help_text='Headings color', max_length=7, verbose_name='Heading Color')),
                ('heading_font', models.CharField(default='system-ui, -apple-system, sans-serif', help_text='Font family for headings', max_length=100, verbose_name='Heading Font')),
                ('body_font', models.CharField(default='system-ui, -apple-system, sans-serif', help_text='Font family for body text', max_length=100, verbose_name='Body Font')),
                ('button_style', models.CharField(choices=[('rounded', 'Rounded'), ('square', 'Square'), ('pill', 'Pill (Full rounded)')], default='rounded', max_length=20, verbose_name='Button Style')),
                ('button_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20, verbose_name='Button Size')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, verbose_name='Key')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('text', 'Text Content'), ('text_image', 'Text + Image'), ('features', 'Features Grid'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('projects_grid', 'Projects Grid'), ('contact_form', 'Contact Form'), ('custom', 'Custom HTML')], max_length=50, verbose_name='Section Type')),
                ('order', models.IntegerField(default=0, help_text='Order of appearance on the page', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('content', models.JSONField(default=dict, help_text='Content with translations: {"translations": {"pt": {...}, "en": {...}}}', verbose_name='Content')),
                ('design', models.JSONField(default=dict, help_text='Visual styling: colors, spacing, alignment, etc.', verbose_name='Design')),
                ('settings', models.JSONField(default=dict, help_text='Functional settings: URLs, behavior, toggles, etc.', verbose_name='Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['page', 'order'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
