# Generated by Django 5.1.1 on 2025-10-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_html_template_to_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If true, this section can be reused across multiple pages', verbose_name='Global Section'),
        ),
    ]
