# Generated by Django 5.1.1 on 2025-10-23 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_section_page_order_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('change_summary', models.CharField(blank=True, default='', max_length=255, verbose_name='Change Summary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.page')),
            ],
            options={
                'verbose_name': 'Page Version',
                'verbose_name_plural': 'Page Versions',
                'ordering': ['-created_at'],
                'unique_together': {('page', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='SectionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('key', models.SlugField(max_length=100, verbose_name='Key')),
                ('section_type', models.CharField(max_length=100, verbose_name='Section Type')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_global', models.BooleanField(default=False, verbose_name='Global Section')),
                ('html_template', models.TextField(blank=True, default='', verbose_name='HTML Template')),
                ('content', models.JSONField(default=dict, verbose_name='Content')),
                ('design', models.JSONField(default=dict, verbose_name='Design')),
                ('settings', models.JSONField(default=dict, verbose_name='Settings')),
                ('page_order_overrides', models.JSONField(blank=True, default=dict, verbose_name='Page Order Overrides')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('change_summary', models.CharField(blank=True, default='', max_length=255, verbose_name='Change Summary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.section')),
            ],
            options={
                'verbose_name': 'Section Version',
                'verbose_name_plural': 'Section Versions',
                'ordering': ['-created_at'],
                'unique_together': {('section', 'version_number')},
            },
        ),
    ]
