# Generated by Django 5.1.1 on 2025-10-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pageversion_sectionversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='excelencia_badge',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_address_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_address_pt',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='livro_reclamacoes_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_1',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_1_note',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_2_note',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_3',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_3_note',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='pme_lider_badge',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='tagline_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='tagline_pt',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='website_by_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='website_by_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='website_by_text_pt',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='website_by_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_briefing',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the project/business for AI context. Include business type, target audience, brand values, tone of voice, and key messaging. This helps AI generate more relevant content.', verbose_name='Project Briefing'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_briefing_en',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the project/business for AI context. Include business type, target audience, brand values, tone of voice, and key messaging. This helps AI generate more relevant content.', null=True, verbose_name='Project Briefing'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_briefing_pt',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the project/business for AI context. Include business type, target audience, brand values, tone of voice, and key messaging. This helps AI generate more relevant content.', null=True, verbose_name='Project Briefing'),
        ),
    ]
