# Generated by Django 5.1.1 on 2025-10-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_design_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Título PT", "en": "Title EN"}', verbose_name='Title (All Languages)'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='alt_text_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Texto alternativo PT", "en": "Alt text EN"}', verbose_name='Alt Text (All Languages)'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Título PT", "en": "Title EN"}', verbose_name='Title (All Languages)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Morada PT", "en": "Address EN"}', verbose_name='Contact Address (All Languages)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_briefing_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Briefing PT", "en": "Briefing EN"}. Detailed description of the project/business for AI context.', verbose_name='Project Briefing (All Languages)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Descrição PT", "en": "Description EN"}', verbose_name='Site Description (All Languages)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Nome do Site", "en": "Site Name"}', verbose_name='Site Name (All Languages)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (OLD)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (OLD)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (OLD)'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text (OLD)'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text (OLD)'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='alt_text_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text (OLD)'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (OLD)'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (OLD)'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='title_pt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address_pt',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Address (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='project_briefing',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Project Briefing (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='project_briefing_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Project Briefing (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='project_briefing_pt',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Project Briefing (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Description (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Description (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Description (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, default='Get Algarve', max_length=100, null=True, verbose_name='Site Name (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(blank=True, default='Get Algarve', max_length=100, null=True, verbose_name='Site Name (OLD)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_pt',
            field=models.CharField(blank=True, default='Get Algarve', max_length=100, null=True, verbose_name='Site Name (OLD)'),
        ),
    ]
