# Generated by Django 5.1.1 on 2025-10-28 00:18

from django.db import migrations
from django.conf import settings


def copy_site_settings_to_json(apps, schema_editor):
    """Copy SiteSettings data from modeltranslation fields to JSON fields"""
    SiteSettings = apps.get_model('core', 'SiteSettings')

    # Get language codes from settings
    languages = [code for code, name in settings.LANGUAGES]

    for obj in SiteSettings.objects.all():
        # Migrate site_name
        obj.site_name_i18n = {}
        for lang in languages:
            field_name = f'site_name_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.site_name_i18n[lang] = value

        # Migrate site_description
        obj.site_description_i18n = {}
        for lang in languages:
            field_name = f'site_description_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.site_description_i18n[lang] = value

        # Migrate contact_address
        obj.contact_address_i18n = {}
        for lang in languages:
            field_name = f'contact_address_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.contact_address_i18n[lang] = value

        # Migrate project_briefing
        obj.project_briefing_i18n = {}
        for lang in languages:
            field_name = f'project_briefing_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.project_briefing_i18n[lang] = value

        obj.save()
        print(f"✓ Migrated SiteSettings: {obj.site_name_i18n}")


def copy_page_to_json(apps, schema_editor):
    """Copy Page data from modeltranslation fields to JSON fields"""
    Page = apps.get_model('core', 'Page')

    languages = [code for code, name in settings.LANGUAGES]

    for obj in Page.objects.all():
        obj.title_i18n = {}
        for lang in languages:
            field_name = f'title_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.title_i18n[lang] = value

        obj.save()
        print(f"✓ Migrated Page: {obj.slug} - {obj.title_i18n}")


def copy_site_image_to_json(apps, schema_editor):
    """Copy SiteImage data from modeltranslation fields to JSON fields"""
    SiteImage = apps.get_model('core', 'SiteImage')

    languages = [code for code, name in settings.LANGUAGES]

    for obj in SiteImage.objects.all():
        # Migrate title
        obj.title_i18n = {}
        for lang in languages:
            field_name = f'title_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.title_i18n[lang] = value

        # Migrate alt_text
        obj.alt_text_i18n = {}
        for lang in languages:
            field_name = f'alt_text_{lang}'
            value = getattr(obj, field_name, None)
            if value:
                obj.alt_text_i18n[lang] = value

        obj.save()
        print(f"✓ Migrated SiteImage: {obj.key or obj.id} - {obj.title_i18n}")


def reverse_migration(apps, schema_editor):
    """Reverse: copy data back from JSON to modeltranslation fields"""
    print("Reversing migration... (copying from JSON back to old fields)")
    # We don't really need to implement this since we're keeping old fields for now
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_page_title_i18n_siteimage_alt_text_i18n_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_site_settings_to_json, reverse_migration),
        migrations.RunPython(copy_page_to_json, reverse_migration),
        migrations.RunPython(copy_site_image_to_json, reverse_migration),
    ]
