# Generated by Django 5.1.1 on 2025-10-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_copy_data_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_pt',
        ),
        migrations.RemoveField(
            model_name='siteimage',
            name='alt_text_en',
        ),
        migrations.RemoveField(
            model_name='siteimage',
            name='alt_text_pt',
        ),
        migrations.RemoveField(
            model_name='siteimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='siteimage',
            name='title_pt',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_address_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_address_pt',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='project_briefing_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='project_briefing_pt',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_description_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_description_pt',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name_pt',
        ),
    ]
