# Generated by Django 5.1.1 on 2025-10-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_page_title_en_remove_page_title_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(default='pt', help_text="Default language code (e.g., 'pt', 'en', 'es')", max_length=10, verbose_name='Default Language'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enabled_languages',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled languages: [{"code": "pt", "name": "Portuguese"}, {"code": "en", "name": "English"}]', verbose_name='Enabled Languages'),
        ),
    ]
