# Generated by Django 5.1.1 on 2025-10-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_copy_slug_to_slug_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageversion',
            name='slug_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "sobre", "en": "about"}', verbose_name='Slug (All Languages)'),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"pt": "Título PT", "en": "Title EN"}', verbose_name='Title (All Languages)'),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug (OLD)'),
        ),
        migrations.AlterField(
            model_name='pageversion',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title (OLD)'),
        ),
    ]
