# Generated by Django 5.1.1 on 2025-10-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_logo_dark_to_logo_dark_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique identifier (e.g., "main-header", "footer")', max_length=100, unique=True, verbose_name='Key')),
                ('section_type', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('announcement', 'Announcement Bar'), ('sidebar', 'Sidebar'), ('custom', 'Custom Global Section')], default='custom', max_length=50, verbose_name='Section Type')),
                ('name', models.CharField(help_text='Display name for admin (e.g., "Main Header", "Footer")', max_length=200, verbose_name='Name')),
                ('html_template', models.TextField(help_text='HTML template with Django template syntax. Use {{trans.field}} for translatable content.', verbose_name='HTML Template')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Translatable content: {"translations": {"pt": {...}, "en": {...}}}', verbose_name='Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('cache_duration', models.IntegerField(default=3600, help_text='How long to cache this section (default: 3600 = 1 hour)', verbose_name='Cache Duration (seconds)')),
                ('fallback_template', models.CharField(blank=True, help_text='Optional: Path to template file as fallback (e.g., "partials/header.html")', max_length=255, verbose_name='Fallback Template Path')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Global Section',
                'verbose_name_plural': 'Global Sections',
                'ordering': ['order', 'key'],
            },
        ),
    ]
