# Generated by Django 5.1.1 on 2026-02-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_sectionversion_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='admin@example.com', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, default='DjangoPress', max_length=100, null=True, verbose_name='Site Name (OLD)'),
        ),
    ]
