# Generated by Django 5.1.1 on 2026-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='domain',
            field=models.CharField(blank=True, default='', help_text='e.g. get-algarve-com — used as the storage folder name in Google Cloud Storage', max_length=255, verbose_name='Site Domain'),
        ),
    ]
