# Generated by Django 6.0.2 on 2026-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_design_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='project_briefing_i18n',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='project_briefing',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the project/business for AI context.', verbose_name='Project Briefing'),
        ),
    ]
