# Generated by Django 6.0.2 on 2026-02-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_sitesettings_custom_body_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='description',
            field=models.TextField(blank=True, default='', help_text='AI-generated semantic description for intelligent image matching', verbose_name='AI Description'),
        ),
    ]
