# Generated by Django 6.0.2 on 2026-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_siteimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_button_bg',
            field=models.CharField(default='#1e3a8a', help_text='Background color for primary buttons', max_length=20, verbose_name='Primary Button Background'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_button_border',
            field=models.CharField(default='#1e3a8a', help_text='Border color for primary buttons', max_length=20, verbose_name='Primary Button Border'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_button_hover',
            field=models.CharField(default='#1e40af', help_text='Hover background color for primary buttons', max_length=20, verbose_name='Primary Button Hover'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_button_text',
            field=models.CharField(default='#ffffff', help_text='Text color for primary buttons', max_length=20, verbose_name='Primary Button Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_button_bg',
            field=models.CharField(default='#64748b', help_text='Background color for secondary buttons', max_length=20, verbose_name='Secondary Button Background'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_button_border',
            field=models.CharField(default='#64748b', help_text='Border color for secondary buttons', max_length=20, verbose_name='Secondary Button Border'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_button_hover',
            field=models.CharField(default='#475569', help_text='Hover background color for secondary buttons', max_length=20, verbose_name='Secondary Button Hover'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_button_text',
            field=models.CharField(default='#ffffff', help_text='Text color for secondary buttons', max_length=20, verbose_name='Secondary Button Text'),
        ),
    ]
