# Generated by Django 6.0.2 on 2026-03-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_widen_button_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='file',
            field=models.FileField(blank=True, help_text='For non-image files (PDFs). Images use the image field above.', null=True, upload_to='site_files/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document')], db_index=True, default='image', max_length=20, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='site_images/', verbose_name='Image'),
        ),
    ]
