# Generated by Django 6.0.2 on 2026-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_siteimage_file_siteimage_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsection',
            name='html_template_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Per-language Django template HTML. Structure: {"pt": "<html>...", "en": "<html>..."}'),
        ),
        migrations.AddField(
            model_name='page',
            name='html_content_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Per-language HTML content. Structure: {"pt": "<html>...", "en": "<html>..."}'),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='html_content_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Per-language HTML content snapshot.'),
        ),
    ]
