# Generated by Django 6.0.2 on 2026-03-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_homepage_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_model_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-task AI model overrides. Keys: generation, refinement, header_footer, translation, metadata, image_analysis, assistant_router, assistant_executor.', verbose_name='AI Model Configuration'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage',
            field=models.ForeignKey(blank=True, help_text='Page to use as the site front page. If not set, the first page by sort order is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.page'),
        ),
    ]
