# Generated by Django 6.0.2 on 2026-03-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_sitesettings_ai_model_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsection',
            name='html_template',
            field=models.TextField(help_text='Legacy field (pre-v1.0). Per-language HTML is now stored in html_template_i18n.', verbose_name='HTML Template'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_content',
            field=models.TextField(blank=True, default='', help_text='Legacy field (pre-v1.0). Per-language HTML is now stored in html_content_i18n.', verbose_name='HTML Content'),
        ),
    ]
