# Generated by Django 6.0.2 on 2026-03-10 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_globalsection_html_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSectionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('html_template_i18n', models.JSONField(blank=True, default=dict)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(blank=True, default='', max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.globalsection')),
            ],
            options={
                'verbose_name': 'Global Section Version',
                'verbose_name_plural': 'Global Section Versions',
                'ordering': ['-created_at'],
                'unique_together': {('section', 'version_number')},
            },
        ),
    ]
