# Generated by Django 6.0.2 on 2026-03-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_globalsectionversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gcs_folder',
            field=models.CharField(blank=True, default='', help_text='Folder name in Google Cloud Storage. Set automatically from the project slug. Do not change after media is uploaded.', max_length=255, verbose_name='GCS Folder'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='domain',
            field=models.CharField(blank=True, default='', help_text='Production domain, e.g. windmillrestaurant.pt', max_length=255, verbose_name='Site Domain'),
        ),
    ]
