# Generated by Django 6.0.2 on 2026-03-18 01:03

from django.db import migrations


def populate_gcs_folder(apps, schema_editor):
    """Copy domain value to gcs_folder for existing sites."""
    SiteSettings = apps.get_model('core', 'SiteSettings')
    for ss in SiteSettings.objects.all():
        if ss.domain and not ss.gcs_folder:
            ss.gcs_folder = ss.domain.replace('.', '-').replace(':', '-')
            ss.save(update_fields=['gcs_folder'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_gcs_folder_to_sitesettings'),
    ]

    operations = [
        migrations.RunPython(populate_gcs_folder, migrations.RunPython.noop),
    ]
