# Generated by Django 6.0.2 on 2026-03-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_populate_gcs_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cookie_consent_enabled',
            field=models.BooleanField(default=True, help_text='Show a GDPR cookie consent banner on all pages', verbose_name='Cookie Consent Banner'),
        ),
    ]
