# Generated by Django 6.1.1 on 2026-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_cookie_consent_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageversion',
            name='kind',
            field=models.CharField(choices=[('auto', 'Auto'), ('checkpoint', 'Checkpoint'), ('undo', 'Undo'), ('redo', 'Redo')], db_index=True, default='auto', help_text='auto = post-save snapshot; checkpoint = state before a user operation; undo/redo = state before an undo/redo ran', max_length=12, verbose_name='Kind'),
        ),
    ]
