# Generated by Django 6.0.2 on 2026-03-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_migrate_newspost_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='content_i18n',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='title',
        ),
    ]
