# Generated by Django 6.0.2 on 2026-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_old_newspost_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Layout identifier: list, detail, category', unique=True)),
                ('html_content_i18n', models.JSONField(blank=True, default=dict, help_text='Per-language HTML layout with Django template syntax', verbose_name='HTML Layout (All Languages)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Layout',
                'verbose_name_plural': 'News Layouts',
            },
        ),
    ]
