# Generated by Django 5.1.1 on 2025-10-23 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Sports Agency", "E-commerce Fashion"', max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('industry', models.CharField(blank=True, help_text='e.g., "Sports scholarship agency for student athletes"', max_length=200, verbose_name='Industry')),
                ('brand_personality', models.TextField(blank=True, help_text='Describe brand character. e.g., "Professional, inspiring, trustworthy, youth-oriented"', verbose_name='Brand Personality')),
                ('design_guidelines', models.TextField(blank=True, help_text='Design rules and preferences. e.g., "Use full-width hero sections, bold typography, gradient overlays on images"', verbose_name='Design Guidelines')),
                ('tone_of_voice', models.TextField(blank=True, help_text='How content should sound. e.g., "Professional but approachable, inspiring, action-oriented"', verbose_name='Tone of Voice')),
                ('key_messages', models.TextField(blank=True, help_text='Core messages to communicate (one per line)', verbose_name='Key Messages')),
                ('content_guidelines', models.TextField(blank=True, help_text='What to include/avoid in content. e.g., "Use statistics, avoid clichés, be transparent"', verbose_name='Content Guidelines')),
                ('seo_keywords_pt', models.TextField(blank=True, help_text='Comma-separated. e.g., "bolsas de estudo, atletas, USA"', verbose_name='SEO Keywords (PT)')),
                ('seo_keywords_en', models.TextField(blank=True, help_text='Comma-separated. e.g., "sports scholarships, athletes, USA"', verbose_name='SEO Keywords (EN)')),
                ('reference_websites', models.TextField(blank=True, help_text='URLs of good design examples (one per line)', verbose_name='Reference Websites')),
                ('html_examples', models.TextField(blank=True, help_text='HTML snippets the LLM can use as reference', verbose_name='HTML Examples')),
                ('design_model', models.CharField(choices=[('claude', 'Claude Sonnet 4.5'), ('gpt-5', 'GPT-5'), ('gemini-pro', 'Gemini Pro')], default='claude', max_length=30, verbose_name='Design Model')),
                ('content_model', models.CharField(choices=[('gemini-flash', 'Gemini Flash'), ('gemini-pro', 'Gemini Pro'), ('claude', 'Claude Sonnet 4.5')], default='gemini-flash', max_length=30, verbose_name='Content Model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generation Context',
                'verbose_name_plural': 'Generation Contexts',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('reference_type', models.CharField(choices=[('screenshot', 'Screenshot'), ('template', 'HTML Template')], max_length=20, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_references/', verbose_name='Screenshot')),
                ('html_template', models.TextField(blank=True, verbose_name='HTML Template')),
                ('section_type', models.CharField(blank=True, help_text='e.g., "hero", "features", "pricing"', max_length=100, verbose_name='Section Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='ai.generationcontext')),
            ],
            options={
                'verbose_name': 'Design Reference',
                'verbose_name_plural': 'Design References',
                'ordering': ['context', 'order', '-created_at'],
            },
        ),
    ]
